name: Export game

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: export game
      uses: firebelley/godot-export@v2.1.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
        godot_template_version: 3.2.1.stable
        relative_project_path: ./
        relative_export_path: ./
        create_release: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.1.5
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: exports/web

    - name: Request Github Pages build job
      run: >-
        curl -L -X POST 
        -H "Content-Type: application/json"
        -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}"
        "https://api.github.com/repos/${{ github.repository }}/pages/builds"

