name: Export game

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: export game
      # Use version 1.0.0 (see releases for all versions)
      uses: firebelley/godot-export@v1.0.1
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_export_templates.tpz
        godot_template_version: 3.1.2.stable
        relative_project_path: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: copy build to repo
      run: cp -R /home/runner/.local/share/godot/builds/0 ./web-build

    - run: ls -la ./web-build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.1.5
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: web-build

    - name: Request Github Pages build job
      run: >-
        curl -L -X POST 
        -H "Content-Type: application/json"
        -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}"
        "https://api.github.com/repos/${{ github.repository }}/pages/builds"

